---
language: node_js
node_js:
  - "6"

sudo: required
dist: trusty

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
    code_climate:
        repo_token:
             secure: "RtTWSoGnbxP7DO4Szr4nM3VQR0utwc8yg7PST4mmLWmfmWsye/3hee41VXsjJLidrRocELm7aiwP3W7YT/OAE8p6lYsvIuqKJKdm0LvQmH4kSWTUbh1398nLPf9Es/bCJy9Z3RrZfvEq5e5JeUG+rSS6u0B2GKOyIrg5fMBw3Ki3J1pV43fuGFJQzgUfF+HbHorr0LjacBrMjXcfR9RPM0MBCQNUarlaWews6AEuNnMRYT7kNW8QeX1bbxG401vNtgC5owEK1xQVJYvWMUnHkzk5pS9mIgNdV++Njh3WIgOSNqPEKZo64SsbYwVXBNrMTnk6ZUg756KhTxXR0i8/6Rhc9et/hKyznRvtkQ58es0XYDjQjseguCgMI3KwEcDAaHyYYAAgM7VCMMQU7Vs4WJjBEpKF2QeqJRevUSsPM9/XqHUYNxPph5NOgdZVN4qYCKJLvZwLbbMBT+CBMn7u+uxvjGSTz9dSleEbf0tnEGnyX0B7v7rqPiEjXXYrGip8lbN8YRR9nHgduTO2B7slSbV2QRtT+qJGBHtHYHDy/XcTsO3ppY1X09YPd+/JVfSYFCpIVoAvr9qIstR7bGtCPmv7j429/6zNF1/umjBVtocX+HLIgVB6WBLttP1pt6BB0oj4r25PHPsQA5s3Lfcwi/+yxzcMXTNIEGtM9tn7HkE="
